(let ([x 42])
  (let ([f1 (future (lambda () 
                     (set! x 10)))])
    (let ([f2 (future (lambda () 
                        (set! x 20)))])
      (touch f1)
      (touch f2)
      (+ 0 x))))
